package com.datasynops.job.entity;

public enum JobEnum {
    NEW,
    VOTER_DATA_UPLOADED,
    CANVAS_CONTENT_UPLOADED,
    CONTENT_GENERATION_IN_PROGRESS,
    CAMPAIGN_READY,
    CANVASING_IN_PROGRESS,
    CANVASING_SUBMITTED,
    MSG_VERIFICATION_IN_PROGRESS,
    CANVASING_PARTIAL_COMPLETE,
    CANVASING_COMPLETED;

    JobEnum() {
    }
}
